version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: shifts-db
    restart: always
    environment:
      POSTGRES_DB: shifts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: shifts-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_IP: postgres
      DB_PORT: 5432
      DB_NAME: shifts
      DB_USER: postgres
      DB_PASSWORD: root
      FRONT_URL: https://turnow.vercel.app/
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
